site_name: Gumon Docs
nav:
  - Home: index.md
  - Gumon cli: gumoncli.md
  - Core Service: coreService.md
  - Application Service: applicationService.md
  - User Service: userService.md
  - สร้าง Service ใหม่: userService.md
theme:
  name: material
