site_name: Gumon Docs
nav:
  - Home: index.md
  - Gumon cli: gumoncli.md
  - Core Service: coreService.md
  - Application Service: applicationService.md
  - Authentication Service: authenticationService.md
  - User Service: userService.md
  - Label Service: labelService.md
  - Notificatoin Service: notificationService.md
  - สร้าง Service ใหม่: createService.md
theme:
  name: material
